branches:
  only:
    master
language:node_js

node_js:
  "v16.13.0"

cache:npm

before_install:
  git config --gobal user.name "ErenLu777"
  git config --gibal user.email "www.1725366837@qq.com"

install:
  npm install
  npm run build

script:
  git log